Add two 575s
Totsugekitai/hanazonochateau.net pull request #15
Opened 2023-07-06 15:09 UTC by ikanago

お手洗いのほうは伊勢神宮で見つけた，由緒正しい575です．ご利益があったりなかったりすると思います．

2023-07-06 15:15 UTC, Totsugekitai requested changes
575の投稿ありがとうございます！
内容は素晴らしいのですが、575の音の区切りを半角スペースで区切って欲しいです。
お手数おかけしますがよろしくお願いします。

2023-07-07 00:12 UTC, Totsugekitai commented
@ikanago すみません、他の人からもプルリクが来て、そちらを先にマージしたためコンフリクトが起きてると思います。
なのでお手数ですが、そちらも解決してから再度レビュー依頼いただけるとありがたいです！

2023-07-07 01:07 UTC, ikanago commented
見落としてました！
スペースの挿入とコンフリクトの解消しました．

2023-07-07 01:17 UTC, Totsugekitai approved these changes

2023-07-07 01:17 UTC, Totsugekitai commented
OKです！ご対応ありがとうございます！

2023-07-07 01:17 UTC, merged